version: "2"

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - redis_data:/data

  taskmanager:
    build: .
    volumes:
      - .:/src
    command: uvicorn src.main:app --host ${APPLICATION_HOST} --port ${DOCKER_EXPOSED_PORT}
    ports:
      - "${APPLICATION_PORT}:${DOCKER_EXPOSED_PORT}"
    restart: always
    env_file:
      - .env
    depends_on:
      - redis

volumes:
  redis_data:
