version: "2"

services:
  taskmanagerdb:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - taskmanagerdb:/var/lib/postgresql/data/
    restart: on-failure

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - redis_data:/data
    depends_on:
      - taskmanagerdb
    restart: on-failure

  taskmanager:
    build: .
    volumes:
      - .:/src
    command: uvicorn src.main:app --host ${APPLICATION_HOST} --port ${DOCKER_EXPOSED_PORT} --reload
    ports:
      - "${APPLICATION_PORT}:${DOCKER_EXPOSED_PORT}"
    env_file:
      - .env
    depends_on:
      - taskmanagerdb
      - redis
    environment:
      - WATCHFILES_FORCE_POLLING=true
    restart: on-failure

volumes:
  taskmanagerdb: null
  redis_data:
