version: "2"

services:
  taskmanagerdb:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - taskmanagerdb:/var/lib/postgresql/data/
    restart: always

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - redis_data:/data
    depends_on:
      - taskmanagerdb

  taskmanager:
    build: .
    volumes:
      - .:/src
    command: uvicorn src.main:app --host ${APPLICATION_HOST} --port ${DOCKER_EXPOSED_PORT}
    ports:
      - "${APPLICATION_PORT}:${DOCKER_EXPOSED_PORT}"
    restart: always
    env_file:
      - .env
    depends_on:
      - taskmanagerdb
      - redis

volumes:
  taskmanagerdb: null
  redis_data:
